create table if not exists desk (
    id uuid generated by default as identity primary key,
    card_id int not null,
    employee_id int not null,
    desk_name varchar(100),
    created date not null,
    updated date,

    foreign key (card_id) references card(id),
    foreign key (employee_id) references employee(id)
);

create table if not exists card(
    id uuid generated by default as identity primary key,
    task_id int not null,
    employee_id int not null,
    card_name varchar(100),
    created date not null,
    updated date,

    foreign key (task_id) references task(id),
    foreign key (employee_id) references employee(id)
);

create table if not exists employee(
    id uuid generated by default as identity primary key,
    employee_name varchar(100) not null,
    employee_email varchar(150) not null,
    employee_password varchar(250) not null,
    created date not null,
    updated date
);

create table if not exists task(
    id uuid generated by default as identity primary key,
    employee_id int not null,
    kind_of_task varchar(30) not null,
    task_name varchar(100) not null,
    created date not null,
    updated date,

    foreign key (employee_id) references employee(id)
);