spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

DATABASE_URL: "jdbc:postgresql://localhost:5432/itone_db"
DATABASE_USERNAME: "postgres"
DATABASE_PASSWORD: "postgres"
DATABASE_DRIVER: "org.postgresql.Driver"
